package SticksCORBAApp;


/**
* SticksCORBAApp/SticksCORBA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SticksCORBA.idl
* 6 Декабрь 2016 г. 12:53:07 MSK
*/

public interface SticksCORBA extends SticksCORBAOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SticksCORBA
