package SticksCORBAApp;

/**
* SticksCORBAApp/SticksCORBAHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SticksCORBA.idl
* 6 Декабрь 2016 г. 12:53:07 MSK
*/

public final class SticksCORBAHolder implements org.omg.CORBA.portable.Streamable
{
  public SticksCORBAApp.SticksCORBA value = null;

  public SticksCORBAHolder ()
  {
  }

  public SticksCORBAHolder (SticksCORBAApp.SticksCORBA initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SticksCORBAApp.SticksCORBAHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SticksCORBAApp.SticksCORBAHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SticksCORBAApp.SticksCORBAHelper.type ();
  }

}
