package SticksCORBAApp;


/**
* SticksCORBAApp/SticksCORBAOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SticksCORBA.idl
* 6 Декабрь 2016 г. 12:53:07 MSK
*/

public interface SticksCORBAOperations 
{
  void clientMove (byte[] coords);
  byte[] serverMove ();
  void shutdown ();
} // interface SticksCORBAOperations
